In [5]:
import numpy as np
import pandas as pd

import green_tsetlin as gt
import green_tsetlin_core as gtc

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing

In [30]:
cali_housing = fetch_california_housing()
X = cali_housing.data
y = cali_housing.target

df = pd.DataFrame(X, columns=cali_housing.feature_names)
df['target'] = y
df.describe()
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [31]:
# loop all features, and convert to 5 binary cats each
for col in df.columns:
    if col == 'target':
        continue
    df[col] = pd.cut(df[col], bins=5, labels=False)
    # make each column 5 binary columns
    df = pd.concat([df, pd.get_dummies(df[col], prefix=col)], axis=1)

df = df.drop(columns=cali_housing.feature_names)


df

,target,MedInc_0,MedInc_1,MedInc_2,MedInc_3,MedInc_4,HouseAge_0,HouseAge_1,HouseAge_2,HouseAge_3,...,Latitude_0,Latitude_1,Latitude_2,Latitude_3,Latitude_4,Longitude_0,Longitude_1,Longitude_2,Longitude_3,Longitude_4
0,4.526,False,False,True,False,False,False,False,False,True,...,False,False,True,False,False,False,True,False,False,False
1,3.585,False,False,True,False,False,False,True,False,False,...,False,False,True,False,False,False,True,False,False,False
2,3.521,False,False,True,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
3,3.413,False,True,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
4,3.422,False,True,False,False,False,False,False,False,False,...,False,False,True,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,0.781,True,False,False,False,False,False,False,True,False,...,False,False,False,True,False,False,True,False,False,False
20636,0.771,True,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
20637,0.923,True,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
20638,0.847,True,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False
20639,0.894,True,False,False,False,False,False,True,False,False,...,False,False,False,True,False,False,True,False,False,False